AM_CPPFLAGS = -DCBB_PRELOAD -DLOG
AM_CXXFLAGS = -Wall -std=c++11
AM_LDFLAGS = -lpthread 

SYNC_FLAG = -DSTRICT_SYNC_DATA -DSYNC_DATA_WITH_REPLY
WRITE_BACK = -DWRITE_BACK
SERVER_WAIT_FLAG = -DBUSY_WAIT
CLIENT_WAIT_FLAG = -DBUSY_WAIT -DSLEEP_YIELD

if DEBUG
AM_CPPFLAGS += -DDEBUG
endif

if USING_CCI
AM_CPPFLAGS += -DCCI ${CCI_LIB}
AM_LDFLAGS += -lcci
else
AM_CPPFLAGS += -DTCP
endif
